# Generated by Django 4.2.1 on 2023-05-09 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptoaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('crypto', models.CharField(max_length=250)),
                ('private_key', models.CharField(max_length=250)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
