# Generated by Django 4.2.1 on 2023-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoaddr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddress',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
