# Generated by Django 4.2.1 on 2023-05-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoaddr_api', '0003_alter_cryptoaddress_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaddress',
            name='created_at',
        ),
    ]
