# Generated by Django 4.2.1 on 2023-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoaddr_api', '0004_remove_cryptoaddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddress',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoaddress',
            name='crypto',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoaddress',
            name='private_key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
